### ISSUE TITLE
ETA not working due to the modified key

### ISSUE THREAD

**Issue by winstonma** [miklcct/js-kmb-api#2]
Here is my [Runkit](https://runkit.com/winstonma/5f9ba1f143fe390019507c5d) result.

Also I'd like to use your code on my module, I could get the `stop.getStoppings()` working but got the following error while running `stopping.getEtas()`:
```
[2020-10-30 04:28:38.780] [ERROR]  (node:2989) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 175)
[2020-10-30 04:28:38.875] [ERROR]  (node:2989) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at isBuf (/opt/magic_mirror/node_modules/socket.io-parser/is-buffer.js:17:15)
    at _removeBlobs (/opt/magic_mirror/node_modules/socket.io-parser/binary.js:128:44)
    at _removeBlobs (/opt/magic_mirror/node_modules/socket.io-parser/binary.js:130:9)
    at _removeBlobs (/opt/magic_mirror/node_modules/socket.io-parser/binary.js:130:9)
    at _removeBlobs (/opt/magic_mirror/node_modules/socket.io-parser/binary.js:130:9)
    at _removeBlobs (/opt/magic_mirror/node_modules/socket.io-parser/binary.js:130:9)
    at _removeBlobs (/opt/magic_mirror/node_modules/socket.io-parser/binary.js:130:9)
    at _removeBlobs (/opt/magic_mirror/node_modules/socket.io-parser/binary.js:130:9)
    at _removeBlobs (/opt/magic_mirror/node_modules/socket.io-parser/binary.js:130:9)
    at _removeBlobs (/opt/magic_mirror/node_modules/socket.io-parser/binary.js:130:9)
```

The error message from [MagicMirror](https://github.com/MichMich/MagicMirror) module but the error message is gone while `stopping.getEtas()` is commented.

Thanks in advance

**Comment by miklcct** [comment]
Can you add a .catch() handler after the promise and show me what happened?

**Comment by winstonma** [comment]
That's the error message with the `.catch()` handler.

```
[2020-10-30 05:48:11.026] [LOG]    Error: Request failed with status code 403
    at createError (/opt/magic_mirror/modules/MMM-HK-KMB/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/magic_mirror/modules/MMM-HK-KMB/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/magic_mirror/modules/MMM-HK-KMB/node_modules/axios/lib/adapters/http.js:244:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    url: 'https://etav3.kmb.hk/?action=geteta',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.20.0'
    },
    params: {
      lang: 'en',
      route: 'N680',
      bound: '1',
      stop_seq: '3',
      service_type: '1',
      vendor_id: 'a380390746b4fa81',
      apiKey: '8C63D044BF6AD73AC3192B673EE7C6D3F47D7AA5',
      ctr: '1051857431'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'json',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    httpsAgent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 12,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function (anonymous)],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'etav3.kmb.hk',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'etav3.kmb.hk',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 10595,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'GET /?action=geteta&lang=en&route=N680&bound=1&stop_seq=3&service_type=1&vendor_id=a380390746b4fa81&apiKey=8C63D044BF6AD73AC3192B673EE7C6D3F47D7AA5&ctr=1051857431 HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/0.20.0\r\n' +
      'Host: etav3.kmb.hk\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 12,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/?action=geteta&lang=en&route=N680&bound=1&stop_seq=3&service_type=1&vendor_id=a380390746b4fa81&apiKey=8C63D044BF6AD73AC3192B673EE7C6D3F47D7AA5&ctr=1051857431',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 403,
      statusMessage: 'Forbidden',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://etav3.kmb.hk/?action=geteta&lang=en&route=N680&bound=1&stop_seq=3&service_type=1&vendor_id=a380390746b4fa81&apiKey=8C63D044BF6AD73AC3192B673EE7C6D3F47D7AA5&ctr=1051857431',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'etav3.kmb.hk',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://etav3.kmb.hk/?action=geteta&lang=en&route=N680&bound=1&stop_seq=3&service_type=1&vendor_id=a380390746b4fa81&apiKey=8C63D044BF6AD73AC3192B673EE7C6D3F47D7AA5&ctr=1051857431',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 403,
    statusText: 'Forbidden',
    headers: {
      'x-powered-by': 'Express',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '36',
      etag: 'W/"24-Qfz8itFHMqLSgajMBCaqI/pfUrk"',
      date: 'Fri, 30 Oct 2020 05:48:06 GMT',
      connection: 'close'
    },
    config: {
      url: 'https://etav3.kmb.hk/?action=geteta',
      method: 'get',
      headers: [Object],
      params: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      responseType: 'json',
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      httpsAgent: [Agent],
      validateStatus: [Function: validateStatus],
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /?action=geteta&lang=en&route=N680&bound=1&stop_seq=3&service_type=1&vendor_id=a380390746b4fa81&apiKey=8C63D044BF6AD73AC3192B673EE7C6D3F47D7AA5&ctr=1051857431 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.20.0\r\n' +
        'Host: etav3.kmb.hk\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/?action=geteta&lang=en&route=N680&bound=1&stop_seq=3&service_type=1&vendor_id=a380390746b4fa81&apiKey=8C63D044BF6AD73AC3192B673EE7C6D3F47D7AA5&ctr=1051857431',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'etav3.kmb.hk',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { error: 'error: incorrect api key' }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

Not sure if it is similar to the Runkit error message.

**Comment by miklcct** [comment]
I believe that the API key I'm using may have changed. Now it doesn't work.

**Comment by winstonma** [comment]
I see. Yes the Website version also having difficulty obtaining the ETA.

**Comment by winstonma** [comment]
@miklcct An idea just raise from my head

Would it be a good idea to put alternate API key on somewhere (e.g. Github Gist)?

**Comment by miklcct** [comment]
fixed with 3.0.0

**Comment by winstonma** [comment]
Hi @miklcct the `getEtas()` returns empty array (it is not throwing error). Do you think it is caused by the modified key?

**Comment by miklcct** [comment]
It seems that the KMB website added a recaptcha into the API

**Comment by winstonma** [comment]
I see.

Just one more question. Should I expect a raise exception or return empty array, under this kind of situation? Thanks for your work.

**Comment by miklcct** [comment]
API key fixed
